import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Visible sidebar: keep Community Guidelines as a top-level category
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Community Guidelines',
      link: {
        type: 'generated-index',
        description: 'Guidelines for the SNRP community.'
      },
      items: [{ type: 'autogenerated', dirName: 'community-guidelines' }],
    },
    {
      type: 'category',
      label: 'Hostility Guidelines',
      link: { type: 'doc', id: 'hostility-guidelines/hostility-guidelines' },
      items: [],
    },
  ],
};

export default sidebars;
